accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

import accounts.views

urlpatterns = [
    url(r'^send_login_email$', accounts.views.send_login_email, name='send_login_email'),
    url(r'^login$', accounts.views.login, name='login'),
    url(r'logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url

from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import url

from lists import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/new$', views.new_list, name='new_list'),
    url(r'^lists/([^/]+)/$', views.view_list, name='view_list'),
    url(r'^lists/([^/]+)/add_item$', views.add_item, name='add_item'),
]

accounts/models.py
from django.db import models
from django.contrib import auth
import uuid

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

class List(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @property
    def name(self):
        return self.item_set.first().text

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None)

    class Meta:
        unique_together = ('list', 'text')

lists/forms.py
# -*- coding: utf-8 -*-
# vim:fenc=utf-8

from django import forms
from lists.models import Item, List
from django.core.exceptions import ValidationError

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': "Enter a to-do item",
                'class': "form-control input-lg",
            }),
        }

        error_messages = {
            'text': {'required': "No puedes crear un item sin texto"},
            'NON_FIELD_ERRORS' : {
                'unique_together' : "Este item ya existe en tu lista"
            },
        }

    def __init__(self, *args, **kwargs):
        lista = kwargs.pop('for_list', None)
        super().__init__(*args, **kwargs)
        self.instance.list = lista

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': self.Meta.error_messages['NON_FIELD_ERRORS'].values()}
            self._update_errors(e)

class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])



class ExistingListItemForm(ItemForm):
    pass

accounts/views.py
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib import messages, auth

from accounts.models import Token

# POST /accounts/send_login_email
def send_login_email(request):
    email = request.POST['email']
    new_token = Token.objects.create(email=email)
    login_url = request.build_absolute_uri(
        reverse('login') + '?token=%s' % new_token.uid
    )

    ebody = 'Use this link to log in:\n\n%s' % login_url

    send_mail(
        'Your login link for Superlists',
        ebody,
        'noreply@superlists',
        [email]
    )
    messages.success(
        request,
        "Check your email, we've sent you a link you can use to log in."
    )

    return redirect('/')

# GET /accounts/login?token={uid}
def login(request):
    uid = request.GET.get('token')
    user = auth.authenticate(uid=uid)
    if user:
        auth.login(request, user)
    return redirect('/')

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError

from lists.models import Item, List
from lists.forms import ItemForm, NewListForm, ExistingListItemForm

from django.contrib.auth import get_user_model

User = get_user_model()

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

# GET /lists/{id}/
# POST /lists/{id}/
def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()

    if request.method == 'POST':
        form = ItemForm(data=request.POST, for_list=list_)
        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, 'list.html', {'list': list_, 'form': form})

def new_list(request):
    form = NewListForm(data=request.POST)

    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})

# GET /lists/users/{email}/
def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">

    <title>To-Do List</title>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Superlists</a>
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Logeado como {{ user.email }}</li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
          </ul>
        {% else %}
        <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
          <input class="form-control" name="email" type="text" placeholder="e-mail"/>
          <button type="submit" class="btn btn-default">Log-in</button>
          {% csrf_token %}
        </form>
        {% endif %}
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">
          {% block my_lists_sidenav %}
          {% endblock %}
        </div>

        <div class="col-md-9">
          <div class="container">
            <div class="row">
              <div class="col-md-6">
                {% if messages %}
                  {% for message in messages %}
                    {% if message.level_tag == 'success' %}
                      <div class="alert alert-success">{{ message }}</div>
                    {% else %}
                      <div class="alert alert-warning">{{ message }}</div>
                    {% endif %}
                  {% endfor %}
                {% endif %}

                <!-- Formulario -->
                <div class="jumbotron form-container">
                  <h1>{% block header_text %}{% endblock %}</h1>
                  {% block list_form %}
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                      <div class="form-group">
                        {{ form.text }}
                      </div>
                      {% csrf_token %}
                      {% if form.errors %}
                        <div class="form-group has-error">
                          <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                      {% endif %}
                    </form>
                  {% endblock %}
                </div>
                {% block table %}{% endblock %}
                {% block extra_content %}{% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="/static/jquery.min.js"></script>
    <script src="/static/lists.js"></script>

    <script>
$(function() {
  window.Superlists.initialize();
});
    </script>
  </body>
</html>

<!-- vim: syn=htmldjango
-->

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

<!-- vim: syn=htmldjango
-->

lists/templates/list.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block my_lists_sidenav %}
  <nav>
    <ul class="nav nav-pills nav-stacked">
      {% for l in user.list_set.all %}
        {% if list.id == l.id %}
          <li class="active" role="presentation"><a href="{% url 'view_list' l.id %}">{{ l.name }}</a></li>
        {% else %}
          <li role="presentation"><a href="{% url 'view_list' l.id %}">{{ l.name }}</a></li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
      <tr>
        <td class="item-counter">{{ forloop.counter }}</td>
        <td>{{ item.text }}</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

<!-- vim:set syn=htmldjango: -->

lists/templates/my_lists.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
  <h2>{{ owner.email }}'s lists</h2>
  <ul>
    {% for list in owner.list_set.all %}
    <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

<!-- vim:set syn=htmldjango: -->